# Generated by Django 4.0.5 on 2022-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreReserva', models.CharField(max_length=30)),
                ('fila', models.IntegerField()),
                ('asiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=15)),
                ('anioDeLanzamiento', models.IntegerField()),
            ],
        ),
    ]
