# Generated by Django 4.0.5 on 2022-06-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_butacas_peliculas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butacas',
            options={'verbose_name_plural': 'Butacas'},
        ),
        migrations.AlterModelOptions(
            name='familiares',
            options={'verbose_name_plural': 'Familiares'},
        ),
        migrations.AlterModelOptions(
            name='peliculas',
            options={'verbose_name_plural': 'Peliculas'},
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='nombre',
            new_name='nombrePelicula',
        ),
    ]
