# Generated by Django 4.0.5 on 2022-07-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='Butacas',
        ),
    ]
