# Generated by Django 4.0.5 on 2022-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_tienda_delete_butacas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
