# Generated by Django 4.0.5 on 2022-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_tienda_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='precio',
            field=models.FloatField(verbose_name='Precio $'),
        ),
    ]
