# Generated by Django 4.0.5 on 2022-07-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_tienda_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
