# Generated by Django 4.0.5 on 2022-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_tienda_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='precioEntrada',
            field=models.IntegerField(default=1, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
