# Generated by Django 4.0.5 on 2022-07-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_peliculas_precioentrada_alter_tienda_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='precioEntrada',
        ),
    ]
