# Generated by Django 4.0.5 on 2022-07-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_peliculas_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
