# Generated by Django 4.0.5 on 2022-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_remove_tienda_imagen_alter_peliculas_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('profesion', models.IntegerField()),
                ('cv', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
