# Generated by Django 4.0.5 on 2022-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_contacto_delete_familiares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='profesion',
            field=models.CharField(max_length=30),
        ),
    ]
