# Generated by Django 4.0.5 on 2022-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_alter_contacto_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cv',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
