# Generated by Django 4.0.5 on 2022-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
