# Generated by Django 4.0.5 on 2022-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_alter_contacto_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/'),
            preserve_default=False,
        ),
    ]
