# Generated by Django 4.0.5 on 2022-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_alter_contacto_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
    ]
