# Generated by Django 4.0.5 on 2022-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0022_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
