# Generated by Django 4.0.5 on 2022-07-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0023_alter_mensaje_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='distinatario',
            new_name='destinatario',
        ),
    ]
