# Generated by Django 4.0.5 on 2022-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0024_rename_distinatario_mensaje_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='destinatario',
            new_name='distinatario',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
