# Generated by Django 4.0.5 on 2022-07-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0025_rename_destinatario_mensaje_distinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='distinatario',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
